---
- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Install sshguard packages
  yum:
    name: "{{ item }}"
    state: "{{ sshguard_pkgs_state }}"
  with_items: "{{ sshguard_pkgs }}"

- name: Create {{ sshguard_sysconfig_path }} from template
  template:
    src: "sysconfig/sshguard.j2"
    dest: "{{ sshguard_sysconfig_path }}"
    owner: root
    group: root
    mode: '0600'
  notify: restart sshguard

- name: Create {{ sshguard_whitelist_path }} from template
  template:
    src: "sshguard/whitelist.j2"
    dest: "{{ sshguard_whitelist_path }}"
    owner: root
    group: root
    mode: '0600'
  notify: restart sshguard

- name: Ensure sshguard is started and enabled on boot
  service:
    name: "{{ sshguard_service }}"
    state: "{{ sshguard_service_state }}"
    enabled: "{{ sshguard_service_enabled }}"
